#+TITLE: babel-login
#+AUTHOR: suyeden
#+EMAIL: 
#+OPTIONS: toc:nil num:nil author:nil creator:nil LaTeX:t \n:t
#+STARTUP: showall

* babel-login

  [![GitHub license](https://img.shields.io/github/license/suyeden/babel-login)](https://github.com/suyeden/babel-login/blob/master/LICENSE)

** 概要
   1989年に公開された押井守監督のアニメ映画「機動警察パトレイバー the Movie」に出てくる、HOS（Hyper Operating System, 篠原重工の帆場暎一が開発したレイバー用OS）のマスターコピーの起動画面を模したパスワード認証プログラム（ログイン画面）です。
   冗談が分かる人だけ楽しんでください。分からない人はぜひネットで検索。
   ジョークプログラム（危険なプログラムではありません）ではありますが、実際にログイン画面としても使えます。
  
   あくまで HOS 「風」なので、一部アレンジを加えています。
   原作同様、ログインに失敗すると画面に「BABEL」という文字が次々と表示され、延々と画面上を流れていきます。

   [[https://suyeden.github.io/softwares/hobby/babel-login/babel.html][ここから実際に動かすことができます。]]
   パスワードは「1999」です。途中で入力ダイアログが表示されるので、そこに入力してください。
   ログインに成功すると、すえーでんのウェブサイトへと飛びます。

** 作者メモ
   Canvas の勉強がてら、HTML5 と CSS、JavaScript で実装しました。
   それ以外の技術は使っていないので、これらのファイルをサーバーに置くなり自分のPCの適当な場所に置くなりして、babel.html にアクセスすればすぐ起動します。
   
   ログイン画面としても一応使えますが、今回は Canvas を用いた2Dアニメーションの実装の勉強を目的として作ったため、パスワード認証部分は JavaScript で文字列一致を検出するだけのものとなっています。
   「セキュリティ的にちょっと...」という人は、データベースを用いるなどして適宜書き換えてください。
   
   完成させることを最優先に書いたので、正直ソースコードは汚いです。
   また一部アレンジを加えていると書きましたが、作者の自己主張が強めなアレンジになっていると思います。
   ライセンスは CC0 ですので、何をしてもらっても構いません。自由に書き換えるなり公開するなり作者に無断でどんどんしてください。
